/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_myplugindemo_NDKTools */

#ifndef _Included_com_example_myplugindemo_NDKTools
#define _Included_com_example_myplugindemo_NDKTools
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
