/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mytest_mytestdemo_TestJni */

#ifndef _Included_com_mytest_mytestdemo_TestJni
#define _Included_com_mytest_mytestdemo_TestJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mytest_mytestdemo_TestJni
 * Method:    getString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mytest_mytestdemo_TestJni_getString
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
